"use client";

import { useState } from "react";

type AcademicianView = "Overview" | "Collaborations" | "Faculty opportunities" | "Workshops & FDPs" | "Research" | "Mentees" | "My profile";

const opportunities = [
  { kind: "Industry workshop", title: "Web architecture for final-year students", partner: "Nexora Labs", date: "Oct 04, 2026", detail: "A practical workshop for 60 CSE students covering production systems and frontend architecture.", color: "violet" },
  { kind: "Faculty immersion", title: "Full-stack industry training", partner: "BluePeak Systems", date: "Oct 14–28, 2026", detail: "Spend two weeks with a product engineering team and bring current practice back to your classroom.", color: "blue" },
  { kind: "Research collaboration", title: "Applied AI in campus operations", partner: "OrbitWorks", date: "Nov 01, 2026", detail: "Co-author a research project exploring responsible AI for student services and institutional analytics.", color: "orange" }
];

const mentees = [
  { name: "Aarav Sharma", initials: "AS", course: "B.Tech CSE · Final year", focus: "Frontend systems", progress: "82%", color: "green" },
  { name: "Nisha Patel", initials: "NP", course: "B.Tech IT · Third year", focus: "Data analytics", progress: "68%", color: "blue" },
  { name: "Kabir Singh", initials: "KS", course: "BCA · Final year", focus: "Backend APIs", progress: "61%", color: "orange" }
];

export function AcademicianPortal({ onLogout }: { onLogout: () => void }) {
  const [view, setView] = useState<AcademicianView>("Overview");
  const [toast, setToast] = useState("");
  function notify(message: string) { setToast(message); window.setTimeout(() => setToast(""), 2800); }

  return <div className="academician-workspace"><AcademicianTopbar onLogout={onLogout} /><div className="academician-body"><aside className="academician-nav"><p className="workspace">ACADEMICIAN WORKSPACE</p><nav>{[["Overview", "▦"], ["Collaborations", "⊕"], ["Faculty opportunities", "⌁"], ["Workshops & FDPs", "◇"], ["Research", "∴"], ["Mentees", "♙"], ["My profile", "○"]].map(([item, icon]) => <button key={item} className={view === item ? "nav active" : "nav"} onClick={() => setView(item as AcademicianView)}><i>{icon}</i>{item}{item === "Collaborations" && <span className="nav-badge">3</span>}</button>)}</nav><div className="academician-nav-help"><b>Collaboration desk</b><p>Need help shaping an industry partnership?</p><button onClick={() => notify("Collaboration desk opened.")}>Talk to the team →</button></div></aside><main className="academician-main"><div className="academician-heading"><div><p className="eyebrow">MONDAY, SEPTEMBER 21 · 2026</p><h1>{view === "Overview" ? "Good morning, Dr. Iyer." : view}</h1><p>{view === "Overview" ? "Your academic–industry network is creating real momentum." : academicianDescription(view)}</p></div>{(view === "Collaborations" || view === "Workshops & FDPs") && <button className="primary" onClick={() => notify(view === "Collaborations" ? "Collaboration request opened." : "Workshop builder opened.")}>＋ {view === "Collaborations" ? "Propose collaboration" : "Create program"}</button>}</div>{toast && <div className="toast">✓ {toast}</div>}{view === "Overview" && <AcademicianOverview setView={setView} notify={notify} />}{view === "Collaborations" && <CollaborationHub notify={notify} />}{view === "Faculty opportunities" && <FacultyOpportunities notify={notify} />}{view === "Workshops & FDPs" && <WorkshopManager notify={notify} />}{view === "Research" && <ResearchHub notify={notify} />}{view === "Mentees" && <MenteeDirectory notify={notify} />}{view === "My profile" && <AcademicianProfile notify={notify} />}</main></div></div>;
}

function academicianDescription(view: AcademicianView) { const copy: Record<AcademicianView, string> = { Overview: "Your academic–industry network is creating real momentum.", Collaborations: "Build structured partnerships that connect expertise with industry demand.", "Faculty opportunities": "Find internships, immersion programs and consultancy opportunities for faculty.", "Workshops & FDPs": "Create practical learning moments for faculty and students.", Research: "Turn shared questions into research with real-world impact.", Mentees: "Support students with guidance connected to their target roles.", "My profile": "Keep your expertise and collaboration preferences current." }; return copy[view]; }

function AcademicianTopbar({ onLogout }: { onLogout: () => void }) { return <div className="academician-topbar"><div className="academician-brand"><span className="academician-mark">M</span><div><b>Dr. Meera Iyer</b><small>Academician workspace · Verified ✓</small></div></div><div className="academician-top-actions"><button className="icon-button">♧<em>3</em></button><button className="academician-user"><span className="avatar">MI</span><span><b>Dr. Meera Iyer</b><small>Computer Science</small></span>⌄</button><button className="logout-button" onClick={onLogout}>Log out</button></div></div>; }

function AcademicianOverview({ setView, notify }: { setView: (view: AcademicianView) => void; notify: (message: string) => void }) { return <><section className="academician-hero"><div><span className="pill">✦ Academic collaboration</span><h2>Bring industry into the<br /><strong>classroom.</strong></h2><p>There are 12 collaboration opportunities aligned with your expertise in web systems and applied AI.</p><button className="primary" onClick={() => setView("Collaborations")}>Explore collaborations →</button></div><div className="academician-hero-orb"><b>12</b><small>ACTIVE FITS</small></div></section><section className="academician-metrics">{[["12", "Active collaborations", "3 awaiting response", "violet"], ["4", "Faculty opportunities", "Matched to your expertise", "blue"], ["86", "Student mentees", "+12 this semester", "green"], ["7", "Verified outcomes", "Across 3 partners", "orange"]].map(([value, label, note, color]) => <article className={`academician-metric card ${color}`} key={label}><span className="academician-metric-icon">{color === "violet" ? "⊕" : color === "blue" ? "⌁" : color === "green" ? "♙" : "◇"}</span><b>{value}</b><strong>{label}</strong><small>{note}</small></article>)}</section><div className="academician-two-col"><section><div className="academician-section-heading"><div><p className="eyebrow">RECOMMENDED FOR YOU</p><h2>Industry opportunities</h2></div><button className="text-button" onClick={() => setView("Collaborations")}>View all →</button></div><div className="academician-opportunity-list">{opportunities.slice(0, 2).map((item) => <OpportunityPreview item={item} key={item.title} notify={notify} />)}</div></section><section className="card academician-attention"><p className="eyebrow">YOUR NEXT MILESTONE</p><h3>Curriculum advisory review</h3><p>BluePeak Systems shared feedback on your full-stack curriculum recommendations.</p><button className="outline" onClick={() => notify("Curriculum advisory workspace opened.")}>Review feedback →</button><div className="academician-attention-foot"><span>Due in</span><b>4 days</b><small>Keep your collaboration moving</small></div></section></div><section><div className="academician-section-heading"><div><p className="eyebrow">MENTORSHIP PULSE</p><h2>Your students are moving forward</h2></div><button className="text-button" onClick={() => setView("Mentees")}>Open mentee directory →</button></div><div className="mentee-preview-list">{mentees.map((mentee) => <MenteeRow mentee={mentee} key={mentee.name} />)}</div></section></>; }

function OpportunityPreview({ item, notify }: { item: typeof opportunities[number]; notify: (message: string) => void }) { return <article className="academician-opportunity card"><div className={`academician-opportunity-icon ${item.color}`}>{item.kind[0]}</div><div><p className="eyebrow">{item.kind}</p><h3>{item.title}</h3><p>{item.partner} · {item.date}</p></div><button className="outline" onClick={() => notify(`Interest recorded for ${item.partner}.`)}>View →</button></article>; }
function CollaborationHub({ notify }: { notify: (message: string) => void }) { return <><section className="academician-banner"><div><p className="eyebrow">ACADEMIA · INDUSTRY</p><h2>Build something useful together.</h2><p>Choose from workshops, faculty immersion, consultancy and research collaborations.</p></div><button className="primary" onClick={() => notify("Collaboration proposal started.")}>＋ Propose collaboration</button></section><div className="academician-opportunity-grid">{opportunities.map((item) => <article className="academician-opportunity-card card" key={item.title}><div className={`academician-opportunity-art ${item.color}`}><span>{item.kind[0]}</span><small>{item.kind.toUpperCase()}</small></div><div className="academician-card-body"><p className="eyebrow">{item.partner}</p><h3>{item.title}</h3><p>{item.detail}</p><div className="academician-card-meta"><span>Starts {item.date}</span><button className="apply" onClick={() => notify(`Interest recorded for ${item.partner}.`)}>Express interest →</button></div></div></article>)}</div></>; }
function FacultyOpportunities({ notify }: { notify: (message: string) => void }) { return <><div className="academician-directory-heading"><div><p className="eyebrow">FACULTY DEVELOPMENT</p><h2>Opportunities for your practice.</h2><p>Industry exposure that makes teaching more current and connected.</p></div><button className="outline" onClick={() => notify("Opportunity filters opened.")}>Filter & sort ⌄</button></div><div className="faculty-opportunity-list">{[["Faculty internship", "Nexora Labs", "Product engineering immersion", "2 weeks", "Remote + Bengaluru", "violet"], ["Industrial training", "BluePeak Systems", "Cloud-native systems for educators", "5 days", "Bengaluru", "blue"], ["Consultancy", "OrbitWorks", "AI adoption in education", "Flexible", "Remote", "orange"], ["FDP", "DataSpring", "Teaching data analytics with real cases", "3 days", "Online", "green"]].map(([kind, partner, title, duration, location, color]) => <article className="faculty-opportunity card" key={title}><div className={`faculty-icon ${color}`}>{kind[0]}</div><div><p className="eyebrow">{kind}</p><h3>{title}</h3><p>{partner} · {location}</p></div><span>{duration}</span><button className="outline" onClick={() => notify(`Application opened for ${title}.`)}>View opportunity →</button></article>)}</div></>; }
function WorkshopManager({ notify }: { notify: (message: string) => void }) { return <><section className="workshop-banner"><div><p className="eyebrow">WORKSHOPS & FDPs</p><h2>Make practical learning repeatable.</h2><p>Coordinate workshops, guest lectures and faculty development programs with your industry network.</p></div><button className="primary" onClick={() => notify("Program builder opened.")}>＋ Create program</button></section><div className="program-grid">{[["Modern web systems", "Guest lecture", "Nexora Labs", "60 students", "Oct 04", "violet"], ["Cloud teaching lab", "FDP", "BluePeak Systems", "42 faculty", "Oct 14", "blue"], ["AI for campus services", "Research talk", "OrbitWorks", "Open registration", "Nov 01", "orange"]].map(([title, kind, partner, audience, date, color]) => <article className="program-card card" key={title}><div className={`program-art ${color}`}><span>◇</span><small>{kind.toUpperCase()}</small></div><p className="eyebrow">{partner}</p><h3>{title}</h3><div><span>{audience}</span><span>{date}</span></div><button className="outline" onClick={() => notify(`${title} program opened.`)}>Manage program →</button></article>)}</div></>; }
function ResearchHub({ notify }: { notify: (message: string) => void }) { return <><section className="research-banner"><div><p className="eyebrow">RESEARCH & CONSULTANCY</p><h2>Questions worth solving with industry.</h2><p>Find partners who can bring data, context and real-world deployment to your research ideas.</p></div><button className="primary" onClick={() => notify("Research proposal started.")}>＋ Start a proposal</button></section><div className="research-grid">{[["Responsible AI for student services", "OrbitWorks", "Seeking academic lead", "Applied AI"], ["Industry-ready curriculum models", "Nexora Labs", "2 co-authors confirmed", "Education technology"], ["Cloud cost optimization", "BluePeak Systems", "Proposal in review", "Cloud systems"]].map(([title, partner, status, domain]) => <article className="research-card card" key={title}><p className="eyebrow">{domain}</p><h3>{title}</h3><p>{partner}</p><span className="research-status">{status}</span><button className="outline" onClick={() => notify(`${title} workspace opened.`)}>Open workspace →</button></article>)}</div></>; }
function MenteeDirectory({ notify }: { notify: (message: string) => void }) { return <><div className="academician-directory-heading"><div><p className="eyebrow">MENTORSHIP DIRECTORY</p><h2>Guide students with context.</h2><p>See progress against each student's target role and skill plan.</p></div><button className="outline" onClick={() => notify("Mentee report prepared.")}>Export report ↓</button></div><div className="mentee-directory-list">{mentees.map((mentee) => <article className="mentee-detail card" key={mentee.name}><div className="avatar">{mentee.initials}</div><div><h3>{mentee.name}</h3><p>{mentee.course}</p><span className="focus-pill">{mentee.focus}</span></div><div className="mentee-progress"><b>{mentee.progress}</b><small>pathway progress</small><span><i style={{ width: mentee.progress }} /></span></div><button className="outline" onClick={() => notify(`${mentee.name}'s mentoring plan opened.`)}>Open plan →</button></article>)}</div></>; }
function MenteeRow({ mentee }: { mentee: typeof mentees[number] }) { return <article className="mentee-row"><div className="avatar">{mentee.initials}</div><div><b>{mentee.name}</b><small>{mentee.focus}</small></div><span className="mentee-row-bar"><i style={{ width: mentee.progress }} /></span><strong>{mentee.progress}</strong></article>; }
function AcademicianProfile({ notify }: { notify: (message: string) => void }) { return <><section className="academician-profile-cover"><div className="academician-profile-logo">MI</div><div><p className="eyebrow">VERIFIED ACADEMICIAN PROFILE</p><h2>Dr. Meera Iyer <span className="verified">✓</span></h2><p>Associate Professor · Computer Science · Northfield Institute</p></div><button className="outline" onClick={() => notify("Academic profile editor opened.")}>Edit profile →</button></section><div className="academician-profile-grid"><article className="card"><p className="eyebrow">EXPERTISE</p><h3>Web systems · Applied AI · Curriculum design</h3><p>Building bridges between academic foundations and current engineering practice.</p><div className="tag-cloud"><span>Web systems</span><span>Applied AI</span><span>Curriculum</span></div></article><article className="card"><p className="eyebrow">COLLABORATION HEALTH</p><div className="profile-health">88<span>/100</span></div><p>Strong partner alignment · 3 active relationships</p></article><article className="card"><p className="eyebrow">CONTACT</p><p>meera.iyer@northfield.edu</p><p>Office 4.12 · CS Department</p><button className="text-button" onClick={() => notify("Contact details editor opened.")}>Manage details →</button></article></div></>; }
