"use client";

import { useState } from "react";

type CompanyView = "Overview" | "Opportunities" | "Assessments" | "Candidates" | "Training" | "Collaborations" | "Company profile";
type Posting = { id: number; title: string; type: string; location: string; applicants: number; status: "Live" | "Draft"; deadline: string; skills: string[] };

const initialPostings: Posting[] = [
  { id: 1, title: "Frontend Developer Intern", type: "Internship", location: "Remote · 6 months", applicants: 46, status: "Live", deadline: "Oct 12, 2026", skills: ["React", "TypeScript", "Git"] },
  { id: 2, title: "Backend Engineer — Graduate", type: "Entry-level job", location: "Bengaluru · Hybrid", applicants: 28, status: "Live", deadline: "Oct 18, 2026", skills: ["Node.js", "REST APIs", "SQL"] },
  { id: 3, title: "Cloud Foundations Bootcamp", type: "Training program", location: "Online · 4 weeks", applicants: 64, status: "Draft", deadline: "Nov 01, 2026", skills: ["AWS", "Docker", "Linux"] }
];

const roleTests = [
  { title: "Frontend Developer", tag: "Engineering", questions: 20, duration: "30 min", attempts: 128, completion: "84%", color: "violet", topics: "HTML · CSS · JavaScript · React" },
  { title: "Backend Developer", tag: "Engineering", questions: 25, duration: "40 min", attempts: 94, completion: "78%", color: "blue", topics: "Node.js · APIs · Databases · Security" },
  { title: "Data Analyst", tag: "Analytics", questions: 18, duration: "25 min", attempts: 67, completion: "91%", color: "orange", topics: "SQL · Statistics · Python · Visualization" },
  { title: "Product Designer", tag: "Design", questions: 16, duration: "35 min", attempts: 42, completion: "88%", color: "green", topics: "Research · UX · Figma · Systems" }
];

const candidates = [
  { name: "Aarav Sharma", initials: "AS", degree: "B.Tech CSE · Northfield Institute", fit: 92, assessment: 88, skills: ["React", "TypeScript", "Git"], status: "New" },
  { name: "Nisha Patel", initials: "NP", degree: "B.Tech IT · Meridian University", fit: 86, assessment: 81, skills: ["React", "REST APIs", "SQL"], status: "Shortlisted" },
  { name: "Kabir Singh", initials: "KS", degree: "BCA · Northfield Institute", fit: 78, assessment: 74, skills: ["JavaScript", "Node.js", "MongoDB"], status: "Assessment pending" }
];

export function CompanyPortal({ onLogout }: { onLogout: () => void }) {
  const [view, setView] = useState<CompanyView>("Overview");
  const [postings, setPostings] = useState(initialPostings);
  const [showPostForm, setShowPostForm] = useState(false);
  const [toast, setToast] = useState("");
  const [selectedTest, setSelectedTest] = useState<string | null>(null);

  function notify(message: string) { setToast(message); window.setTimeout(() => setToast(""), 2800); }
  function addPosting(posting: Omit<Posting, "id" | "applicants" | "status">) { setPostings((current) => [{ ...posting, id: Date.now(), applicants: 0, status: "Draft" }, ...current]); setShowPostForm(false); notify("Opportunity saved as a draft."); }

  return <div className="company-workspace"><div className="company-topbar"><div className="company-workspace-brand"><span className="mini-logo">N</span><div><b>Nexora Labs</b><small>Company workspace · Verified ✓</small></div></div><div className="company-top-actions"><button className="icon-button">♧<em>4</em></button><button className="company-user"><span className="avatar">NL</span><span><b>Nexora Labs</b><small>Talent team</small></span>⌄</button><button className="logout-button" onClick={onLogout}>Log out</button></div></div><div className="company-body"><aside className="company-nav"><p className="workspace">COMPANY WORKSPACE</p><nav>{[["Overview", "▦"], ["Opportunities", "⌁"], ["Assessments", "◌"], ["Candidates", "♙"], ["Training", "◇"], ["Collaborations", "⊕"], ["Company profile", "□"]].map(([item, icon]) => <button key={item} className={view === item ? "nav active" : "nav"} onClick={() => setView(item as CompanyView)}><i>{icon}</i>{item}{item === "Candidates" && <span className="nav-badge">8</span>}</button>)}</nav><div className="company-nav-help"><b>Talent playbook</b><p>Learn how to attract and assess job-ready campus talent.</p><button onClick={() => notify("Talent playbook opened.")}>Read guide →</button></div></aside><main className="company-main"><div className="company-heading"><div><p className="eyebrow">MONDAY, SEPTEMBER 21 · 2026</p><h1>{view === "Overview" ? "Good morning, Nexora." : view}</h1><p>{view === "Overview" ? "Here is what is moving across your talent pipeline." : view === "Assessments" ? "Create structured assessments for every role you hire." : view === "Opportunities" ? "Publish internships, jobs and training programs." : "Make better campus hiring decisions with verified signals."}</p></div>{view === "Opportunities" && <button className="primary" onClick={() => setShowPostForm(true)}>＋ Post opportunity</button>}</div>{toast && <div className="toast">✓ {toast}</div>}{view === "Overview" && <Overview postings={postings} setView={setView} notify={notify} />}{view === "Opportunities" && <OpportunityManager postings={postings} onPost={() => setShowPostForm(true)} notify={notify} />}{view === "Assessments" && <AssessmentManager selectedTest={selectedTest} setSelectedTest={setSelectedTest} notify={notify} />}{view === "Candidates" && <CandidateManager notify={notify} />}{view === "Training" && <TrainingManager notify={notify} />}{view === "Collaborations" && <CollaborationManager notify={notify} />}{view === "Company profile" && <CompanyProfile notify={notify} />}</main></div>{showPostForm && <PostForm onClose={() => setShowPostForm(false)} onSubmit={addPosting} />}{selectedTest && <TestPreview title={selectedTest} onClose={() => setSelectedTest(null)} onNotify={notify} />}</div>;
}

function Overview({ postings, setView, notify }: { postings: Posting[]; setView: (view: CompanyView) => void; notify: (message: string) => void }) { return <><section className="company-hero"><div><span className="pill">✦ Talent intelligence</span><h2>Turn your open roles into<br /><strong>meaningful matches.</strong></h2><p>There are 148 verified candidates aligned with your active requirements. Your next best hire is closer than you think.</p><button className="primary" onClick={() => setView("Candidates")}>Explore candidate matches →</button></div><div className="pipeline-orb"><b>86%</b><small>AVG. ROLE FIT</small></div></section><section className="company-metrics">{[["12", "Active opportunities", "+3 this month", "green"], ["148", "Qualified candidates", "+18 this week", "blue"], ["34", "Applications received", "8 need review", "orange"], ["76%", "Assessment completion", "+9% this month", "violet"]].map(([value, label, note, color]) => <article className={`company-metric card ${color}`} key={label}><span className="metric-icon">{color === "green" ? "↗" : color === "blue" ? "♙" : color === "orange" ? "▣" : "◌"}</span><b>{value}</b><strong>{label}</strong><small>{note}</small></article>)}</section><div className="company-two-col"><section><div className="company-section-heading"><div><p className="eyebrow">RECRUITMENT PIPELINE</p><h2>Open opportunities</h2></div><button className="text-button" onClick={() => setView("Opportunities")}>Manage all →</button></div><div className="compact-postings">{postings.slice(0, 3).map((posting) => <CompactPosting posting={posting} key={posting.id} />)}</div></section><section className="card attention-card"><p className="eyebrow">NEEDS YOUR ATTENTION</p><h3>8 new candidates are ready for review.</h3><p>Review matched candidates and send role-specific assessments to keep your pipeline moving.</p><button className="outline" onClick={() => setView("Candidates")}>Review candidates →</button><div className="attention-rule"><span>Latest activity</span><b>12 applications</b><small>received in the last 7 days</small></div></section></div><section><div className="company-section-heading"><div><p className="eyebrow">QUICK ACTIONS</p><h2>Keep the momentum going</h2></div></div><div className="quick-actions"><button onClick={() => notify("Opportunity form opened.")}><span>＋</span><b>Post an opportunity</b><small>Internship, job or project</small></button><button onClick={() => setView("Assessments")}><span>◌</span><b>Build an assessment</b><small>Test skills for a role</small></button><button onClick={() => setView("Training")}><span>◇</span><b>Launch training</b><small>Upskill future talent</small></button></div></section></>; }

function CompactPosting({ posting }: { posting: Posting }) { return <article className="compact-posting"><div className={`posting-icon ${posting.status === "Live" ? "live" : "draft"}`}>{posting.title[0]}</div><div><b>{posting.title}</b><p>{posting.type} · {posting.location}</p></div><span className={posting.status === "Live" ? "status-live" : "status-draft"}>{posting.status}</span><strong>{posting.applicants}<small> applicants</small></strong></article>; }

function OpportunityManager({ postings, onPost, notify }: { postings: Posting[]; onPost: () => void; notify: (message: string) => void }) { return <><div className="filter-row"><div className="filter-tabs"><button className="selected">All opportunities <span>{postings.length}</span></button><button>Live <span>{postings.filter((posting) => posting.status === "Live").length}</span></button><button>Drafts <span>{postings.filter((posting) => posting.status === "Draft").length}</span></button></div><button className="outline compact-button" onClick={() => notify("Opportunity filters opened.")}>Filter & sort ⌄</button></div><div className="posting-grid">{postings.map((posting) => <article className="posting-card card" key={posting.id}><div className="posting-card-top"><div className={`posting-icon ${posting.status === "Live" ? "live" : "draft"}`}>{posting.title[0]}</div><span className={posting.status === "Live" ? "status-live" : "status-draft"}>{posting.status}</span></div><p className="eyebrow">{posting.type.toUpperCase()}</p><h3>{posting.title}</h3><p className="posting-location">⌖ {posting.location}</p><div className="skills">{posting.skills.map((skill) => <span key={skill}>{skill}</span>)}</div><div className="posting-card-bottom"><div><b>{posting.applicants}</b><small> applicants</small></div><div><b>{posting.deadline}</b><small> deadline</small></div></div><button className="outline" onClick={() => notify(`${posting.title} editor opened.`)}>Manage posting →</button></article>)}<button className="new-post-card" onClick={onPost}><span>＋</span><b>Post a new opportunity</b><small>Reach verified student talent</small></button></div></>; }

function AssessmentManager({ selectedTest, setSelectedTest, notify }: { selectedTest: string | null; setSelectedTest: (test: string | null) => void; notify: (message: string) => void }) { return <><section className="assessment-intro"><div><p className="eyebrow">ROLE-BASED SCREENING</p><h2>Every role deserves the right signal.</h2><p>Build short, fair assessments that measure the skills your opportunities actually need. Candidates see the assessment before applying.</p></div><button className="primary" onClick={() => notify("Assessment builder opened.")}>＋ Create assessment</button></section><div className="test-grid">{roleTests.map((test) => <article className="test-card card" key={test.title}><div className="test-top"><div className={`test-icon ${test.color}`}>{test.title[0]}</div><span>{test.tag}</span></div><h3>{test.title}</h3><p>{test.topics}</p><div className="test-facts"><span>⌁ {test.questions} questions</span><span>◷ {test.duration}</span></div><div className="test-performance"><div><b>{test.attempts}</b><small>attempts</small></div><div><b>{test.completion}</b><small>completion</small></div></div><div className="test-actions"><button className="outline" onClick={() => setSelectedTest(test.title)}>Preview test</button><button className="text-button" onClick={() => notify(`${test.title} editor opened.`)}>Edit →</button></div></article>)}</div></>; }

function CandidateManager({ notify }: { notify: (message: string) => void }) { return <><div className="candidate-summary"><div><p className="eyebrow">CANDIDATE DISCOVERY</p><h2>People who could move your team forward.</h2><p>Compatibility combines role skills, assessment results, education and preferences.</p></div><button className="outline" onClick={() => notify("Candidate export prepared.")}>Export shortlist ↓</button></div><div className="candidate-toolbar"><div className="filter-tabs"><button className="selected">All <span>148</span></button><button>New <span>8</span></button><button>Shortlisted <span>24</span></button><button>Assessment pending <span>17</span></button></div><input className="search" placeholder="⌕  Search candidates" /></div><div className="candidate-table card"><div className="candidate-table-head"><span>Candidate</span><span>Role fit</span><span>Assessment</span><span>Skills</span><span>Next action</span></div>{candidates.map((candidate) => <div className="candidate-row" key={candidate.name}><div className="candidate-person"><div className="avatar">{candidate.initials}</div><div><b>{candidate.name}</b><small>{candidate.degree}</small></div></div><div><b className="fit-number">{candidate.fit}%</b><small>match</small></div><div><b>{candidate.assessment}%</b><small>{candidate.status}</small></div><div className="skills">{candidate.skills.map((skill) => <span key={skill}>{skill}</span>)}</div><button className="outline" onClick={() => notify(`${candidate.name}'s profile opened.`)}>View profile →</button></div>)}</div></>; }

function TrainingManager({ notify }: { notify: (message: string) => void }) { return <><section className="training-banner"><div><p className="eyebrow">INDUSTRY LEARNING</p><h2>Train the talent you want to hire.</h2><p>Publish workshops, bootcamps and certification pathways. Students who complete them build verified evidence in their portfolio.</p></div><button className="primary" onClick={() => notify("Training program builder opened.")}>＋ Create training</button></section><div className="training-grid">{[["Cloud Foundations Bootcamp", "64 enrolled", "4 weeks", "green"], ["Modern React Workshop", "42 enrolled", "2 days", "violet"], ["API Design Masterclass", "28 enrolled", "3 sessions", "blue"]].map(([title, enrolled, duration, color]) => <article className="training-card card" key={title}><div className={`training-art ${color}`}><span>◇</span><small>LIVE PROGRAM</small></div><p className="eyebrow">CERTIFICATE PATHWAY</p><h3>{title}</h3><div><span>{enrolled}</span><span>{duration}</span></div><button className="outline" onClick={() => notify(`${title} details opened.`)}>Manage program →</button></article>)}</div></>; }

function CollaborationManager({ notify }: { notify: (message: string) => void }) { return <><section className="collaboration-banner"><p className="eyebrow">ACADEMIA · INDUSTRY</p><h2>Make your expertise part of the curriculum.</h2><p>Partner with institutions for workshops, guest lectures, live projects, research and faculty immersion.</p><button className="primary" onClick={() => notify("Collaboration request started.")}>Start a collaboration →</button></section><div className="collab-company-grid">{[["Northfield Institute", "Curriculum advisory", "2 active projects", "NI"], ["Meridian University", "Guest lecture series", "Next session · Oct 04", "MU"], ["Eastshore College", "Industry project", "Applications open", "EC"]].map(([name, type, status, initials]) => <article className="card partner-card" key={name}><div className="avatar">{initials}</div><p className="eyebrow">{type}</p><h3>{name}</h3><p>{status}</p><button className="outline" onClick={() => notify(`${name} collaboration opened.`)}>Open workspace →</button></article>)}</div></>; }

function CompanyProfile({ notify }: { notify: (message: string) => void }) { return <section className="company-profile-page"><div className="company-profile-cover"><div className="company-profile-logo">N</div><div><p className="eyebrow">VERIFIED INDUSTRY PARTNER</p><h2>Nexora Labs <span className="verified">✓</span></h2><p>Product engineering · Bengaluru · 201–500 employees</p></div><button className="outline" onClick={() => notify("Company profile editor opened.")}>Edit profile →</button></div><div className="profile-sections"><article className="card"><p className="eyebrow">ABOUT NEXORA</p><h3>Building products that make complex work feel simple.</h3><p>We partner with universities to create practical learning pathways in product engineering, cloud and data.</p></article><article className="card"><p className="eyebrow">PARTNERSHIP HEALTH</p><div className="health-score">92<span>/100</span></div><p>Trusted partner · Verification renewed Aug 2026</p></article><article className="card"><p className="eyebrow">CONTACT & LINKS</p><p>talent@nexoralabs.com</p><p>nexoralabs.com ↗</p><button className="text-button" onClick={() => notify("Contact details editor opened.")}>Manage details →</button></article></div></section>; }

function PostForm({ onClose, onSubmit }: { onClose: () => void; onSubmit: (posting: Omit<Posting, "id" | "applicants" | "status">) => void }) { const [title, setTitle] = useState(""); const [type, setType] = useState("Internship"); const [location, setLocation] = useState(""); const [deadline, setDeadline] = useState(""); const [skills, setSkills] = useState(""); return <div className="modal-backdrop"><form className="modal-card post-form" onSubmit={(event) => { event.preventDefault(); onSubmit({ title: title || "Untitled opportunity", type, location: location || "Remote", deadline: deadline || "To be announced", skills: skills.split(",").map((skill) => skill.trim()).filter(Boolean) }); }}><div className="modal-head"><div><p className="eyebrow">NEW OPPORTUNITY</p><h2>Post an opportunity</h2></div><button type="button" className="modal-close" onClick={onClose}>×</button></div><p className="modal-intro">Tell students what they will learn, build and contribute.</p><label>Role title<input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="e.g. Frontend Developer Intern" autoFocus /></label><div className="form-two"><label>Opportunity type<select value={type} onChange={(event) => setType(event.target.value)}><option>Internship</option><option>Entry-level job</option><option>Live project</option><option>Training program</option></select></label><label>Location<input value={location} onChange={(event) => setLocation(event.target.value)} placeholder="Remote or city · work mode" /></label></div><div className="form-two"><label>Application deadline<input type="date" value={deadline} onChange={(event) => setDeadline(event.target.value)} /></label><label>Required skills<input value={skills} onChange={(event) => setSkills(event.target.value)} placeholder="React, Git, APIs" /></label></div><label>Role assessment<select><option>Frontend Developer assessment</option><option>Backend Developer assessment</option><option>Data Analyst assessment</option><option>No assessment</option></select></label><div className="modal-actions"><button type="button" className="outline" onClick={onClose}>Cancel</button><button className="primary" type="submit">Save as draft →</button></div></form></div>; }

function TestPreview({ title, onClose, onNotify }: { title: string; onClose: () => void; onNotify: (message: string) => void }) { const [selected, setSelected] = useState(1); return <div className="modal-backdrop"><section className="modal-card test-preview"><div className="modal-head"><div><p className="eyebrow">ASSESSMENT PREVIEW · 01 / 05</p><h2>{title} screening</h2></div><button className="modal-close" onClick={onClose}>×</button></div><div className="preview-progress"><span /></div><p className="preview-topic">JavaScript fundamentals · single choice</p><h3>Which approach best describes a pure function?</h3><div className="preview-options">{["It changes global state", "It returns the same output for the same input", "It always performs an API call", "It can only be written as a class"].map((option, index) => <button key={option} className={selected === index ? "chosen" : ""} onClick={() => setSelected(index)}><b>{String.fromCharCode(65 + index)}</b>{option}</button>)}</div><div className="modal-actions"><button className="outline" onClick={onClose}>Close preview</button><button className="primary" onClick={() => { onClose(); onNotify("Assessment assigned to selected candidates."); }}>Assign assessment →</button></div></section></div>; }
