"use client";

import { useState } from "react";

type InstitutionView = "Overview" | "Students" | "Analytics" | "Industry partners" | "Interventions" | "Reports" | "Institution profile";

const cohorts = [
  { department: "Computer Science", students: 284, assessed: "86%", readiness: "78%", gap: "REST APIs", color: "green" },
  { department: "Information Technology", students: 236, assessed: "74%", readiness: "71%", gap: "Cloud fundamentals", color: "blue" },
  { department: "Electronics & Communication", students: 198, assessed: "61%", readiness: "64%", gap: "Data analytics", color: "orange" },
  { department: "Mechanical Engineering", students: 172, assessed: "58%", readiness: "57%", gap: "Automation", color: "violet" }
];

const partners = [
  { name: "Nexora Labs", initials: "N", focus: "Product engineering", opportunities: 14, status: "Active", color: "green" },
  { name: "BluePeak Systems", initials: "B", focus: "Cloud & full stack", opportunities: 9, status: "Active", color: "blue" },
  { name: "OrbitWorks", initials: "O", focus: "Applied research", opportunities: 6, status: "Renewal due", color: "orange" }
];

export function InstitutionPortal({ onLogout }: { onLogout: () => void }) {
  const [view, setView] = useState<InstitutionView>("Overview");
  const [toast, setToast] = useState("");
  function notify(message: string) { setToast(message); window.setTimeout(() => setToast(""), 2800); }

  return <div className="institution-workspace"><InstitutionTopbar onLogout={onLogout} /><div className="institution-body"><aside className="institution-nav"><p className="workspace">INSTITUTION WORKSPACE</p><nav>{[["Overview", "▦"], ["Students", "♙"], ["Analytics", "◌"], ["Industry partners", "⊕"], ["Interventions", "◇"], ["Reports", "□"], ["Institution profile", "○"]].map(([item, icon]) => <button key={item} className={view === item ? "nav active" : "nav"} onClick={() => setView(item as InstitutionView)}><i>{icon}</i>{item}{item === "Reports" && <span className="nav-badge">2</span>}</button>)}</nav><div className="institution-nav-help"><b>Placement playbook</b><p>Turn readiness signals into targeted student support.</p><button onClick={() => notify("Placement playbook opened.")}>Read guide →</button></div></aside><main className="institution-main"><div className="institution-heading"><div><p className="eyebrow">MONDAY, SEPTEMBER 21 · 2026</p><h1>{view === "Overview" ? "Good morning, Northfield." : view}</h1><p>{view === "Overview" ? "Your institution-wide career readiness snapshot is ready." : institutionDescription(view)}</p></div>{view === "Reports" && <button className="primary" onClick={() => notify("New report builder opened.")}>＋ Create report</button>}</div>{toast && <div className="toast">✓ {toast}</div>}{view === "Overview" && <InstitutionOverview setView={setView} notify={notify} />}{view === "Students" && <StudentDirectory notify={notify} />}{view === "Analytics" && <InstitutionAnalytics />}{view === "Industry partners" && <PartnerDirectory notify={notify} />}{view === "Interventions" && <InterventionCenter notify={notify} />}{view === "Reports" && <InstitutionReports notify={notify} />}{view === "Institution profile" && <InstitutionProfile notify={notify} />}</main></div></div>;
}

function institutionDescription(view: InstitutionView) { const copy: Record<InstitutionView, string> = { Overview: "Your institution-wide career readiness snapshot is ready.", Students: "Monitor skill growth and placement readiness across every cohort.", Analytics: "Understand which skills are improving and where support is needed.", "Industry partners": "Build a stronger bridge between your students and industry.", Interventions: "Move from a skill-gap signal to a focused development plan.", Reports: "Share clear outcomes with leadership and placement stakeholders.", "Institution profile": "Keep your institution and placement cell information current." }; return copy[view]; }

function InstitutionTopbar({ onLogout }: { onLogout: () => void }) { return <div className="institution-topbar"><div className="institution-brand"><span className="institution-mark">N</span><div><b>Northfield Institute</b><small>Institution workspace · Verified ✓</small></div></div><div className="institution-top-actions"><button className="icon-button">♧<em>5</em></button><button className="institution-user"><span className="avatar">NI</span><span><b>Placement Cell</b><small>Administrator</small></span>⌄</button><button className="logout-button" onClick={onLogout}>Log out</button></div></div>; }

function InstitutionOverview({ setView, notify }: { setView: (view: InstitutionView) => void; notify: (message: string) => void }) { return <><section className="institution-hero"><div><span className="pill">✦ Institution intelligence</span><h2>See what moves your<br /><strong>students forward.</strong></h2><p>Use current skill, opportunity and placement signals to focus your next intervention where it matters most.</p><button className="primary" onClick={() => setView("Analytics")}>Open institution analytics →</button></div><div className="institution-hero-orb"><b>72%</b><small>READY</small></div></section><section className="institution-metrics">{[["1,248", "Students tracked", "+84 this term", "green"], ["72%", "Placement readiness", "+6% from last term", "blue"], ["763", "Assessments completed", "64% of active students", "orange"], ["36", "Industry partners", "+4 this term", "violet"]].map(([value, label, note, color]) => <article className={`institution-metric card ${color}`} key={label}><span className="institution-metric-icon">{color === "green" ? "♙" : color === "blue" ? "↗" : color === "orange" ? "◌" : "⊕"}</span><b>{value}</b><strong>{label}</strong><small>{note}</small></article>)}</section><div className="institution-two-col"><section><div className="institution-section-heading"><div><p className="eyebrow">READINESS SNAPSHOT</p><h2>By department</h2></div><button className="text-button" onClick={() => setView("Students")}>View students →</button></div><div className="readiness-list">{cohorts.slice(0, 3).map((cohort) => <ReadinessRow cohort={cohort} key={cohort.department} />)}</div></section><section className="card institution-alert"><p className="eyebrow">ACTION NEEDED</p><h3>REST APIs is the most common gap.</h3><p>184 students across CSE and IT are below the target level for active industry roles.</p><button className="outline" onClick={() => setView("Interventions")}>Create intervention →</button><div className="institution-alert-foot"><span>Industry demand</span><b>42 open roles</b><small>currently request this skill</small></div></section></div><section><div className="institution-section-heading"><div><p className="eyebrow">RECENT ACTIVITY</p><h2>Keep the institution moving</h2></div></div><div className="institution-quick-actions"><button onClick={() => setView("Interventions")}><span>◇</span><b>Plan a skill intervention</b><small>Target the biggest gaps</small></button><button onClick={() => setView("Industry partners")}><span>⊕</span><b>Connect an industry partner</b><small>Grow your opportunity network</small></button><button onClick={() => notify("Placement report download started.")}><span>↓</span><b>Download placement report</b><small>Leadership-ready summary</small></button></div></section></>; }

function ReadinessRow({ cohort }: { cohort: { department: string; students: number; assessed: string; readiness: string; gap: string; color: string } }) { return <article className="readiness-row"><span className={`department-dot ${cohort.color}`} /><div><b>{cohort.department}</b><small>{cohort.students} students · {cohort.assessed} assessed</small></div><div className="readiness-bar"><span style={{ width: cohort.readiness }} /></div><strong>{cohort.readiness}</strong><em>{cohort.gap}</em></article>; }

function StudentDirectory({ notify }: { notify: (message: string) => void }) { return <><div className="directory-summary"><div><p className="eyebrow">STUDENT SUCCESS DIRECTORY</p><h2>Understand every cohort.</h2><p>Filter students by readiness, department, assessment completion or skill gap.</p></div><button className="outline" onClick={() => notify("Student directory export prepared.")}>Export directory ↓</button></div><div className="directory-toolbar"><div className="filter-tabs"><button className="selected">All students <span>1,248</span></button><button>Needs support <span>184</span></button><button>Placement ready <span>392</span></button></div><input className="search" placeholder="⌕  Search students or department" /></div><div className="institution-cohort-table card"><div className="institution-table-head"><span>Department</span><span>Students</span><span>Assessed</span><span>Readiness</span><span>Priority gap</span><span>Action</span></div>{cohorts.map((cohort) => <div className="institution-table-row" key={cohort.department}><div><span className={`department-dot ${cohort.color}`} /><b>{cohort.department}</b></div><span>{cohort.students}</span><span>{cohort.assessed}</span><strong className="readiness-number">{cohort.readiness}</strong><span className="gap-label">{cohort.gap}</span><button className="outline" onClick={() => notify(`${cohort.department} cohort opened.`)}>View cohort →</button></div>)}</div></>; }

function InstitutionAnalytics() { return <><section className="analytics-hero"><div><p className="eyebrow">TERM PERFORMANCE · 2026</p><h2>Readiness is moving in the right direction.</h2><p>Students who complete an assessment and targeted learning plan are 2.4× more likely to reach placement-ready status.</p></div><div className="analytics-hero-stat"><b>+6%</b><small>readiness growth</small></div></section><div className="analytics-kpis">{[["78%", "CSE readiness", "↑ 8%"], ["71%", "IT readiness", "↑ 5%"], ["64%", "ECE readiness", "↑ 3%"], ["57%", "ME readiness", "↑ 4%"]].map(([value, label, delta]) => <div className="card analytics-kpi" key={label}><b>{value}</b><span>{label}</span><small>{delta}</small></div>)}</div><div className="institution-chart-grid"><section className="card institution-chart-card"><p className="eyebrow">READINESS TREND</p><h3>Average readiness by month</h3><div className="line-chart"><span style={{ height: "38%" }} /><span style={{ height: "44%" }} /><span style={{ height: "47%" }} /><span style={{ height: "56%" }} /><span style={{ height: "60%" }} /><span style={{ height: "72%" }} /></div><div className="chart-labels"><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span><span>Sep</span></div></section><section className="card demand-card"><p className="eyebrow">INDUSTRY DEMAND</p><h3>Most requested skills</h3>{[["REST APIs", "42 roles", "82%"], ["Data Analytics", "31 roles", "64%"], ["Cloud Fundamentals", "28 roles", "57%"], ["System Design", "19 roles", "41%"]].map(([skill, roles, value]) => <div className="demand-row" key={skill}><div><b>{skill}</b><small>{roles}</small></div><div className="demand-bar"><span style={{ width: value }} /></div></div>)}</section></div></>; }

function PartnerDirectory({ notify }: { notify: (message: string) => void }) { return <><div className="directory-summary"><div><p className="eyebrow">INDUSTRY NETWORK</p><h2>Partners who create pathways.</h2><p>Track active collaborations, opportunity volume and partner health.</p></div><button className="primary" onClick={() => notify("Partner invitation opened.")}>＋ Invite partner</button></div><div className="partner-grid">{partners.map((partner) => <article className="partner-institution-card card" key={partner.name}><div className="partner-card-top"><div className={`partner-institution-logo ${partner.color}`}>{partner.initials}</div><span className={partner.status === "Active" ? "status-live" : "status-draft"}>{partner.status}</span></div><h3>{partner.name}</h3><p>{partner.focus}</p><div className="partner-card-stats"><span><b>{partner.opportunities}</b><small>opportunities</small></span><span><b>{partner.status === "Active" ? "92%" : "—"}</b><small>partner health</small></span></div><button className="outline" onClick={() => notify(`${partner.name} workspace opened.`)}>Open partnership →</button></article>)}</div></>; }

function InterventionCenter({ notify }: { notify: (message: string) => void }) { return <><section className="intervention-banner"><div><p className="eyebrow">CLOSED-LOOP DEVELOPMENT</p><h2>Turn skill gaps into action plans.</h2><p>Create targeted learning cohorts and connect them with industry mentors, courses and assessments.</p></div><button className="primary" onClick={() => notify("Intervention builder opened.")}>＋ New intervention</button></section><div className="intervention-list">{[["REST APIs accelerator", "CSE + IT · 184 students", "Assessment → workshop → project", "68% enrolled", "green"], ["Cloud foundations pathway", "IT + ECE · 126 students", "Training → certification", "42% enrolled", "blue"], ["Data analytics readiness", "All departments · 212 students", "Mentor circle → portfolio", "31% enrolled", "orange"]].map(([title, cohort, flow, progress, color]) => <article className="intervention-row card" key={title}><span className={`intervention-icon ${color}`}>◇</span><div><p className="eyebrow">ACTIVE PLAN</p><h3>{title}</h3><p>{cohort}</p></div><span className="intervention-flow">{flow}</span><div className="intervention-progress"><b>{progress}</b><span><i style={{ width: progress.split("%")[0] + "%" }} /></span></div><button className="outline" onClick={() => notify(`${title} plan opened.`)}>Manage →</button></article>)}</div></>; }

function InstitutionReports({ notify }: { notify: (message: string) => void }) { return <div className="report-grid">{[["Placement readiness report", "Leadership", "Updated Sep 18, 2026", "PDF"], ["Industry demand report", "Curriculum committee", "Updated Sep 15, 2026", "PDF"], ["Student skill growth report", "Placement cell", "Updated Sep 12, 2026", "XLSX"], ["Partner impact report", "Executive office", "Updated Aug 31, 2026", "PDF"]].map(([title, audience, updated, format]) => <article className="report-card card" key={title}><span className="report-file">{format}</span><p className="eyebrow">INSTITUTION REPORT</p><h3>{title}</h3><p>{audience} · {updated}</p><button className="outline" onClick={() => notify(`${title} download started.`)}>Download report ↓</button></article>)}</div>; }

function InstitutionProfile({ notify }: { notify: (message: string) => void }) { return <><section className="institution-profile-cover"><div className="institution-profile-logo">N</div><div><p className="eyebrow">VERIFIED INSTITUTION</p><h2>Northfield Institute <span className="verified">✓</span></h2><p>Autonomous · Bengaluru · 8,400 active learners</p></div><button className="outline" onClick={() => notify("Institution profile editor opened.")}>Edit profile →</button></section><div className="institution-profile-grid"><article className="card"><p className="eyebrow">ABOUT THE INSTITUTION</p><h3>Learning that leads somewhere.</h3><p>Northfield Institute partners with industry to make academic learning practical, measurable and connected to opportunity.</p></article><article className="card"><p className="eyebrow">VERIFICATION HEALTH</p><div className="profile-health">96<span>/100</span></div><p>Documents verified · Renewal due Jan 2027</p></article><article className="card"><p className="eyebrow">PLACEMENT CELL</p><p>placements@northfield.edu</p><p>+91 80 4000 2100</p><button className="text-button" onClick={() => notify("Placement cell details editor opened.")}>Manage details →</button></article></div></>; }
