type Role = "student" | "company" | "institution" | "academician";

const roleCopy: Record<Role, { title: string; description: string; icon: string }> = {
  student: { title: "Shape your career with clarity.", description: "Assess your skills, discover relevant opportunities, and build a verified portfolio.", icon: "✦" },
  company: { title: "Meet talent with real potential.", description: "Find skill-matched candidates and create meaningful campus connections.", icon: "⌁" },
  institution: { title: "Make every career outcome visible.", description: "Use skill, opportunity, and placement signals to empower your students.", icon: "▦" },
  academician: { title: "Connect knowledge with practice.", description: "Build industry collaborations, workshops, and research opportunities.", icon: "◌" }
};

export function LoginScreen({ role, onRoleChange, onSignIn }: { role: Role; onRoleChange: (role: Role) => void; onSignIn: () => void }) {
  const copy = roleCopy[role];
  return <main className="login-shell"><section className="login-story"><div className="login-brand"><span className="brand-mark">C</span><span>Campus<span>Bridge</span></span></div><div className="login-copy"><span className="login-icon">{copy.icon}</span><p className="eyebrow">ACADEMIA × INDUSTRY</p><h1>{copy.title}</h1><p>{copy.description}</p></div><div className="login-loop"><span>Industry demand</span><i>→</i><span>Skill growth</span><i>→</i><span>Real opportunity</span></div></section><section className="login-form-area"><div className="login-form"><p className="eyebrow">WELCOME TO CAMPUSBRIDGE</p><h2>Sign in to your workspace</h2><p className="form-intro">Choose a role to preview the platform experience.</p><div className="login-roles">{(Object.keys(roleCopy) as Role[]).map((item) => <button key={item} onClick={() => onRoleChange(item)} className={role === item ? "chosen" : ""}><span>{roleCopy[item].icon}</span><div><b>{item[0].toUpperCase() + item.slice(1)}</b><small>{item === "student" ? "Learn and get matched" : item === "company" ? "Discover talent" : item === "institution" ? "Track outcomes" : "Collaborate with industry"}</small></div></button>)}</div><label>Email address<input type="email" placeholder="name@college.edu" defaultValue={role === "student" ? "aarav@northfield.edu" : ""} /></label><label>Password<input type="password" placeholder="Enter your password" /></label><div className="login-options"><label><input type="checkbox" /> Remember me</label><button>Forgot password?</button></div><button className="login-submit" onClick={onSignIn}>Continue as {role[0].toUpperCase() + role.slice(1)} <span>→</span></button><div className="login-divider"><span>or</span></div><button className="sso-button" onClick={onSignIn}>G&nbsp;&nbsp; Continue with Google</button><p className="signup">New to CampusBridge? <button>Create an account</button></p><p className="demo-note">Demo mode — no credentials are required.</p></div></section></main>;
}
