type Role = "company" | "institution" | "academician";

const data = {
  company: { lead: "Find talent that is ready to contribute.", text: "Your roles have high-signal candidates waiting to be discovered.", action: "Post an opportunity", metrics: [["12", "Active opportunities", "+3 this month"], ["148", "Qualified candidates", "+18 this week"], ["34", "Applications received", "8 need review"]] },
  institution: { lead: "See what moves your students forward.", text: "Use live skill and placement signals to shape your next intervention.", action: "View analytics report", metrics: [["72%", "Placement readiness", "+6% from last term"], ["1,248", "Students tracked", "763 assessed"], ["36", "Industry partners", "+4 this term"]] },
  academician: { lead: "Bring industry into the classroom.", text: "Explore collaborations that make learning practical and relevant.", action: "Explore collaborations", metrics: [["12", "Active collaborations", "3 awaiting review"], ["4", "Faculty opportunities", "Matched to your expertise"], ["86", "Student mentees", "+12 this semester"]] }
};

export function RoleDashboard({ role }: { role: Role }) {
  const item = data[role];
  return <section className="role-dashboard"><div className={`role-hero ${role}`}><div><span className="pill">✦ {role === "company" ? "Verified industry partner" : role === "institution" ? "Institution intelligence" : "Academic collaboration"}</span><h2>{item.lead}</h2><p>{item.text}</p><button className="primary">{item.action} <span>→</span></button></div><div className="role-orb"><b>{role === "company" ? "48" : role === "institution" ? "72%" : "12"}</b><small>{role === "company" ? "TOP MATCHES" : role === "institution" ? "READY" : "ACTIVE"}</small></div></div><div className="metrics">{item.metrics.map(([value, label, note]) => <article className="metric card" key={label}><b>{value}</b><span>{label}</span><small>{note}</small></article>)}</div>{role === "company" && <CompanyContent />}{role === "institution" && <InstitutionContent />}{role === "academician" && <AcademicianContent />}</section>;
}

function Heading({ title, text, action }: { title: string; text: string; action: string }) { return <div className="section-title"><div><h2>{title}</h2><p>{text}</p></div><button className="text-button">{action} →</button></div>; }
function CompanyContent() { return <><Heading title="High-fit candidates" text="Ranked by verified skills, assessments and role requirements." action="View candidate pool" /><div className="candidate-list">{[["Aarav Sharma", "B.Tech CSE · 2026", "86%", "AS"], ["Nisha Patel", "B.Tech IT · 2026", "82%", "NP"], ["Kabir Singh", "BCA · 2025", "77%", "KS"]].map(([name, degree, score, initials]) => <article className="candidate card" key={name}><div className="avatar">{initials}</div><div><h3>{name}</h3><p>{degree}</p><div className="skills"><span>React</span><span>JavaScript</span><span>Git</span></div></div><div className="candidate-score"><b>{score}</b><small>MATCH</small><button className="outline">View profile →</button></div></article>)}</div></>; }
function InstitutionContent() { return <><Heading title="Skill development pulse" text="A clear view of the areas that need focused support." action="Download report" /><article className="analytics-card card"><div><p className="eyebrow">CAREER READINESS BY DEPARTMENT</p><div className="chart">{[72, 64, 58, 82, 49, 68].map((height, i) => <span key={i} style={{ height: `${height}%` }} />)}</div><div className="chart-labels"><span>CSE</span><span>IT</span><span>ECE</span><span>ME</span><span>CE</span><span>EE</span></div></div><aside><b>Top industry demand</b><p>REST APIs</p><p>Data analytics</p><p>Cloud fundamentals</p></aside></article></>; }
function AcademicianContent() { return <><Heading title="Recommended industry collaborations" text="Selected for your expertise and academic interests." action="Browse all" /><div className="collab-grid">{[["Industry workshop", "Nexora Labs", "Web architecture for final-year students", "Oct 04"], ["Faculty immersion", "BluePeak Systems", "Two-week full-stack industry training", "Oct 14"], ["Research collaboration", "OrbitWorks", "Applied AI in campus operations", "Nov 01"]].map(([kind, partner, detail, date]) => <article className="collaboration card" key={partner}><p className="eyebrow">{kind}</p><h3>{partner}</h3><p>{detail}</p><footer><span>Starts {date}</span><button className="apply">Express interest →</button></footer></article>)}</div></>; }
