"use client";

import { useMemo, useState } from "react";

type Category = "Technical skills" | "Programming skills" | "Domain-specific knowledge" | "Aptitude" | "Communication skills" | "Problem-solving ability" | "Other relevant soft skills";
type Phase = "select" | "questions" | "result";
type Question = { category: Category; prompt: string; options: string[]; answer: number; explanation: string };

const categoryDetails: { name: Category; short: string; description: string }[] = [
  { name: "Technical skills", short: "Tools & systems", description: "Technology concepts required for your target role" },
  { name: "Programming skills", short: "Code & logic", description: "Programming fundamentals and implementation" },
  { name: "Domain-specific knowledge", short: "Role expertise", description: "Knowledge directly connected to your chosen role" },
  { name: "Aptitude", short: "Reasoning", description: "Numerical, verbal and logical reasoning" },
  { name: "Communication skills", short: "Clarity", description: "Written and workplace communication" },
  { name: "Problem-solving ability", short: "Approach", description: "How you investigate and solve new problems" },
  { name: "Other relevant soft skills", short: "Work style", description: "Teamwork, ownership, adaptability and leadership" }
];

const commonQuestions: Question[] = [
  { category: "Aptitude", prompt: "A sprint has 24 tasks and a team completes 75% of them. How many tasks remain?", options: ["4", "6", "8", "18"], answer: 1, explanation: "75% of 24 is 18, so 6 tasks remain." },
  { category: "Aptitude", prompt: "What comes next in this sequence: 2, 6, 12, 20, 30, ?", options: ["36", "40", "42", "44"], answer: 2, explanation: "The differences are 4, 6, 8, 10, then 12; 30 + 12 = 42." },
  { category: "Communication skills", prompt: "A requirement is unclear before a deadline. What is the strongest response?", options: ["Guess and deliver silently", "Ask a focused clarifying question and confirm the assumption", "Wait until someone notices", "Skip the requirement"], answer: 1, explanation: "Clarifying early reduces risk and gives the team a shared understanding." },
  { category: "Communication skills", prompt: "Which update is most useful to a project stakeholder?", options: ["It is fine", "I am busy", "The API integration is blocked by auth credentials; I need access by Thursday", "No update"], answer: 2, explanation: "A useful update gives status, impact and a concrete next action." },
  { category: "Problem-solving ability", prompt: "A feature works locally but fails in production. What should you do first?", options: ["Rewrite the whole feature", "Compare environment variables and reproduce the failure with logs", "Blame the deployment tool", "Delete the production data"], answer: 1, explanation: "A controlled comparison and evidence from logs narrows the cause safely." },
  { category: "Problem-solving ability", prompt: "What is the best first step when a bug report is vague?", options: ["Close it", "Ask for reproducible steps, expected behavior and actual behavior", "Change random code", "Assign it without reading"], answer: 1, explanation: "Reproduction details turn an ambiguous report into an actionable problem." },
  { category: "Other relevant soft skills", prompt: "A teammate is blocked and the deadline is close. What demonstrates ownership?", options: ["Ignore it because it is not your task", "Offer help, understand the blocker and agree on the next step", "Take over without telling them", "Escalate immediately without context"], answer: 1, explanation: "Ownership supports the team while keeping communication and responsibility clear." },
  { category: "Other relevant soft skills", prompt: "A constructive response to feedback is to…", options: ["Defend every decision", "Thank the reviewer, clarify what matters and apply the useful change", "Avoid future reviews", "Ask someone else to respond"], answer: 1, explanation: "Feedback is most valuable when it is understood and converted into improvement." }
];

const roleQuestions: Record<string, Question[]> = {
  "Frontend Developer": [
    { category: "Technical skills", prompt: "Which HTML element is the best semantic choice for the primary navigation?", options: ["<div>", "<nav>", "<span>", "<b>"], answer: 1, explanation: "The nav element communicates navigation semantics to browsers and assistive technology." },
    { category: "Technical skills", prompt: "Which CSS layout system is best for aligning items in one dimension?", options: ["Flexbox", "Float only", "Absolute positioning", "Table markup"], answer: 0, explanation: "Flexbox is designed for one-dimensional row or column layout." },
    { category: "Programming skills", prompt: "What does Array.prototype.map return?", options: ["A new transformed array", "Only the first item", "A boolean", "The original array only"], answer: 0, explanation: "map returns a new array containing the callback result for each item." },
    { category: "Programming skills", prompt: "What is a closure in JavaScript?", options: ["A CSS rule", "A function retaining access to its lexical scope", "A database query", "A browser tab"], answer: 1, explanation: "A closure preserves access to variables from the scope where the function was created." },
    { category: "Domain-specific knowledge", prompt: "Why should a React list item have a stable key?", options: ["To style the item", "To help React identify changes efficiently", "To encrypt the item", "To make the API faster"], answer: 1, explanation: "Stable keys help React reconcile list changes correctly." },
    { category: "Domain-specific knowledge", prompt: "What is the most important first step for an accessible interactive button?", options: ["Use a clickable div", "Use a native button element with a clear label", "Hide its focus state", "Add only a color change"], answer: 1, explanation: "Native controls provide keyboard and assistive technology behavior by default." }
  ],
  "Backend Developer": [
    { category: "Technical skills", prompt: "Which HTTP status code indicates a successful resource creation?", options: ["200", "201", "301", "404"], answer: 1, explanation: "201 Created indicates that a request successfully created a resource." },
    { category: "Technical skills", prompt: "What is the main purpose of database indexing?", options: ["Encrypt rows", "Speed up lookups", "Remove backups", "Replace validation"], answer: 1, explanation: "Indexes provide faster access paths for commonly queried data." },
    { category: "Programming skills", prompt: "What does async/await help manage?", options: ["CSS layout", "Asynchronous operations with readable control flow", "Image compression only", "Database schema names"], answer: 1, explanation: "async/await makes promise-based asynchronous code easier to read and handle." },
    { category: "Programming skills", prompt: "Which structure is commonly used for first-in-first-out processing?", options: ["Stack", "Queue", "Tree", "Graph"], answer: 1, explanation: "A queue removes items in the same order they were added." },
    { category: "Domain-specific knowledge", prompt: "Why should an API validate input on the server?", options: ["Clients are always trusted", "To protect data and enforce consistent rules", "To improve CSS", "To avoid logging"], answer: 1, explanation: "Server-side validation protects the system even when clients are modified or bypassed." },
    { category: "Domain-specific knowledge", prompt: "What does idempotent mean for an API operation?", options: ["It always fails", "Repeating it has the same intended effect as doing it once", "It has no response", "It only works offline"], answer: 1, explanation: "An idempotent operation can be repeated without changing the intended result after the first success." }
  ],
  "Full Stack Developer": [
    { category: "Technical skills", prompt: "Which layer should normally enforce authorization for protected data?", options: ["Only the browser", "The server/API", "Only CSS", "The URL color"], answer: 1, explanation: "Authorization must be enforced server-side because browser code can be modified." },
    { category: "Technical skills", prompt: "What does a REST API commonly use to represent resources?", options: ["URLs and HTTP methods", "Only local files", "CSS selectors", "Keyboard shortcuts"], answer: 0, explanation: "REST uses resource-oriented URLs and standard HTTP methods." },
    { category: "Programming skills", prompt: "What is the purpose of a reusable component?", options: ["Duplicate bugs", "Encapsulate UI behavior and reduce repetition", "Disable testing", "Hide all data"], answer: 1, explanation: "Components package reusable UI and behavior into maintainable units." },
    { category: "Programming skills", prompt: "Which Git operation creates a separate line of work?", options: ["branch", "status", "clone only", "log"], answer: 0, explanation: "A branch provides an independent line of development." },
    { category: "Domain-specific knowledge", prompt: "What is a good full-stack error-handling practice?", options: ["Expose stack traces to users", "Return safe errors and log useful diagnostic context", "Ignore all errors", "Retry forever"], answer: 1, explanation: "Users need safe messages while developers need diagnostic logs." },
    { category: "Domain-specific knowledge", prompt: "Why are automated tests valuable in a full-stack project?", options: ["They remove the need for design", "They catch regressions across changing layers", "They replace version control", "They guarantee zero bugs"], answer: 1, explanation: "Tests provide repeatable checks as frontend, API and data layers evolve." }
  ],
  "Data Analyst": [
    { category: "Technical skills", prompt: "Which SQL clause filters rows before grouping?", options: ["WHERE", "HAVING", "GROUP BY", "ORDER BY"], answer: 0, explanation: "WHERE filters rows before aggregation and grouping." },
    { category: "Technical skills", prompt: "Which chart is usually best for showing a trend over time?", options: ["Line chart", "Pie chart", "Single number", "Word cloud"], answer: 0, explanation: "Line charts make changes across an ordered time axis easy to see." },
    { category: "Programming skills", prompt: "What is a common use of Python in analytics?", options: ["Data cleaning and analysis", "CSS-only styling", "DNS registration", "Keyboard firmware only"], answer: 0, explanation: "Python provides strong libraries and workflows for cleaning and analyzing data." },
    { category: "Programming skills", prompt: "What does a loop allow a program to do?", options: ["Repeat logic", "Delete the database", "Change a URL", "Create a password automatically"], answer: 0, explanation: "Loops repeat a block of logic while a condition or collection requires it." },
    { category: "Domain-specific knowledge", prompt: "What is the purpose of checking for missing values?", options: ["Make the dataset larger", "Avoid misleading calculations and choose a treatment", "Change all values to zero", "Remove documentation"], answer: 1, explanation: "Missing data can bias analysis, so it needs to be understood and handled deliberately." },
    { category: "Domain-specific knowledge", prompt: "What makes a metric actionable?", options: ["It has no owner", "A team can make a decision or take action based on it", "It is always huge", "It is never reviewed"], answer: 1, explanation: "Actionable metrics connect measurement to a decision or intervention." }
  ],
  "Product Designer": [
    { category: "Technical skills", prompt: "What does a design system provide?", options: ["Only a logo", "Reusable patterns, components and usage guidance", "A database backup", "A hiring policy"], answer: 1, explanation: "Design systems create consistency through shared patterns and guidance." },
    { category: "Technical skills", prompt: "Why test a prototype with representative users?", options: ["To validate assumptions and discover usability issues", "To avoid questions", "To make screens heavier", "To replace all research"], answer: 0, explanation: "Testing reveals whether real users can understand and complete the intended tasks." },
    { category: "Programming skills", prompt: "What does a component state usually control in an interface?", options: ["Dynamic UI behavior", "The company legal name", "A server IP only", "A font license"], answer: 0, explanation: "State represents changing data that affects what the interface renders." },
    { category: "Programming skills", prompt: "Which format is commonly used to exchange structured data with an API?", options: ["JSON", "MP3", "PNG", "TTF"], answer: 0, explanation: "JSON is a common lightweight format for structured API data." },
    { category: "Domain-specific knowledge", prompt: "What is an affordance in interface design?", options: ["A clue about how an element can be used", "A database index", "A deployment script", "A legal document"], answer: 0, explanation: "Affordances communicate possible actions through appearance and behavior." },
    { category: "Domain-specific knowledge", prompt: "What should a user journey map capture?", options: ["Only color choices", "User goals, actions, pain points and touchpoints", "Only source code", "Server memory"], answer: 1, explanation: "Journey maps connect user goals and emotions to the steps and touchpoints of an experience." }
  ]
};

function questionsFor(role: string, categories: Category[]) { return [...(roleQuestions[role] ?? roleQuestions["Frontend Developer"]), ...commonQuestions].filter((question) => categories.includes(question.category)).slice(0, 14); }

export function StudentAssessmentFlow({ initialRole, notify }: { initialRole: string; notify: (message: string) => void }) {
  const [phase, setPhase] = useState<Phase>("select");
  const [role, setRole] = useState(initialRole || "Frontend Developer");
  const [categories, setCategories] = useState<Category[]>(categoryDetails.map((category) => category.name));
  const [questions, setQuestions] = useState<Question[]>([]);
  const [answers, setAnswers] = useState<Record<number, number>>({});
  const [current, setCurrent] = useState(0);
  const [error, setError] = useState("");
  const [score, setScore] = useState(0);
  const toggleCategory = (category: Category) => setCategories((selected) => selected.includes(category) ? selected.filter((item) => item !== category) : [...selected, category]);
  const categoryScores = useMemo(() => categoryDetails.map((category) => { const items = questions.filter((question) => question.category === category.name); const correct = items.filter((question, index) => answers[questions.indexOf(question)] === question.answer).length; return { ...category, total: items.length, correct }; }).filter((item) => item.total > 0), [questions, answers]);

  function start() { const generated = questionsFor(role, categories); if (categories.length < 5 || generated.length < 10) { setError("Select at least five assessment modules to create a 10-question assessment."); return; } setQuestions(generated); setAnswers({}); setCurrent(0); setError(""); setPhase("questions"); }
  function submit() { const unanswered = questions.findIndex((_, index) => answers[index] === undefined); if (unanswered !== -1) { setCurrent(unanswered); setError("Answer every question before submitting."); return; } const result = questions.reduce((total, question, index) => total + (answers[index] === question.answer ? 1 : 0), 0); setScore(result); setError(""); setPhase("result"); notify("Assessment submitted. Your skill profile was calculated."); }
  if (phase === "questions") { const question = questions[current]; return <section className="assessment-flow"><div className="assessment-flow-head"><div><p className="eyebrow">{role.toUpperCase()} · SKILL ASSESSMENT</p><h2>Show what you know.</h2></div><span>{current + 1} / {questions.length}</span></div><div className="assessment-progress"><i style={{ width: `${((current + 1) / questions.length) * 100}%` }} /></div><article className="assessment-question card"><div className="question-meta"><span>{question.category}</span><small>Question {current + 1}</small></div><h3>{question.prompt}</h3><div className="assessment-options">{question.options.map((option, index) => <button key={option} className={answers[current] === index ? "selected" : ""} onClick={() => setAnswers((existing) => ({ ...existing, [current]: index }))}><b>{String.fromCharCode(65 + index)}</b>{option}</button>)}</div></article>{error && <p className="assessment-error">{error}</p>}<div className="assessment-flow-actions"><button className="outline" disabled={current === 0} onClick={() => { setError(""); setCurrent((value) => Math.max(0, value - 1)); }}>← Previous</button>{current < questions.length - 1 ? <button className="primary" onClick={() => { setError(""); setCurrent((value) => value + 1); }}>Next question →</button> : <button className="primary" onClick={submit}>Submit assessment →</button>}</div></section>; }
  if (phase === "result") { const percentage = Math.round((score / questions.length) * 100); const gaps = categoryScores.filter((item) => item.correct / item.total < 0.7); return <section className="assessment-result-page"><div className="assessment-result-hero"><span className="result-check">✓</span><p className="eyebrow">ASSESSMENT COMPLETE · {role.toUpperCase()}</p><h2>Your skill profile is ready.</h2><div className="assessment-final-score"><b>{percentage}%</b><small>{score} of {questions.length} correct</small></div><p>Your responses have been converted into skill signals and gap recommendations.</p></div><div className="assessment-result-grid"><section className="card result-breakdown"><p className="eyebrow">SKILL PROFILE</p><h3>Performance by category</h3>{categoryScores.map((item) => <div className="result-category" key={item.name}><div><b>{item.name}</b><span>{item.correct}/{item.total}</span></div><span><i style={{ width: `${(item.correct / item.total) * 100}%` }} /></span></div>)}</section><section className="card result-gaps"><p className="eyebrow">SKILL GAPS</p><h3>Recommended focus areas</h3>{gaps.length ? gaps.map((gap) => <div className="result-gap" key={gap.name}><span>◇</span><div><b>{gap.name}</b><small>Build this skill with a learning plan</small></div></div>) : <p className="result-success">Great foundation. Keep practicing to stay role-ready.</p>}<button className="outline" onClick={() => notify("Learning recommendations opened.")}>View learning recommendations →</button></section></div><div className="assessment-result-actions"><button className="outline" onClick={() => setPhase("select")}>Change role or modules</button><button className="primary" onClick={() => { setPhase("select"); notify("Assessment reset. Choose your next focus."); }}>Retake assessment →</button></div></section>; }
  return <section className="assessment-flow"><div className="assessment-selection-hero"><div><p className="eyebrow">SKILL ASSESSMENT CENTER</p><h2>Assess the skills your target role needs.</h2><p>Select a role and the competency modules you want to measure. We will generate a role-aligned assessment before calculating your skill profile and gaps.</p></div><div className="assessment-flow-steps"><span className="active">1<br /><small>Choose</small></span><i>→</i><span>2<br /><small>Questions</small></span><i>→</i><span>3<br /><small>Results</small></span></div></div><section className="assessment-config card"><div className="assessment-config-heading"><div><p className="eyebrow">TARGET ROLE</p><h3>What role are you preparing for?</h3></div><select value={role} onChange={(event) => setRole(event.target.value)}><option>Frontend Developer</option><option>Backend Developer</option><option>Full Stack Developer</option><option>Data Analyst</option><option>Product Designer</option></select></div><div className="assessment-config-heading modules"><div><p className="eyebrow">ASSESSMENT MODULES</p><h3>Choose what to evaluate</h3><small>Select at least 5 modules · 2 questions per module</small></div><span>{categories.length}/7 selected</span></div><div className="assessment-module-grid">{categoryDetails.map((category) => <button type="button" key={category.name} className={categories.includes(category.name) ? "assessment-module selected" : "assessment-module"} onClick={() => toggleCategory(category.name)}><span>{categories.includes(category.name) ? "✓" : "○"}</span><div><b>{category.name}</b><small>{category.description}</small></div></button>)}</div>{error && <p className="assessment-error">{error}</p>}<div className="assessment-config-footer"><p>Generated assessment: <b>{Math.min(14, categories.length * 2)} questions</b> · Technical, programming, domain and soft-skill signals included</p><button className="primary" onClick={start}>Start assessment →</button></div></section></section>;
}
